language: c
dist: precise
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
  os:
    - linux
    - osx
  allow_failures:
    - os: osx

script:
  - sudo ./install.sh
  - sudo ./runTests.sh
  - sudo ./runPerfTests.sh
  - sudo ./runRegTests.sh

branches:
  only:
  - master
