language: c

sudo: required

script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - ./install.sh
  - ./runTests.sh

branches:
  only:
  - master
