language: c

sudo: required

os:
  - linux
  - osx

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
  allow_failures:
    - os: osx

script:
  - sudo ./install.sh
  - sudo ./runTests.sh

branches:
  only:
  - master
