language: c

sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

script:
  - ./install.sh
  - ./runTests.sh

branches:
  only:
  - master
